name: Docker Image CI

on:
  #push:
   # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  backend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with: 
        python-version: ${{matrix.python-version}}

    - name : Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt

    - name : Start Backend server
      run: |
        cd backend 
        python app.py

  build_and_serve:
    runs-on: ubuntu-latest
    #needs: backend

    steps:

    - name: checkout code
      uses: actions/checkout@v2


    # Step 2: Set up Node.js (for installing npm dependencies and running build)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you want to use

      # Step 3: Navigate to the frontend directory
    - name: Navigate to frontend directory and install dependencies
      run: |
        cd frontend
        npm install  # Install dependencies

      # Step 4: Build static content for production
    - name: Build static content for production
      run: |
        cd frontend
        npm run build  # Build the static files (make sure this command is defined in your package.json)

      # Step 5: Install the `serve` package globally
    - name: Install serve
      run: npm install -g serve  # Install the `serve` package globally

      # Step 6: Serve the static content
    - name: Serve the static content
      run: |
        cd frontend
        serve -s build  # Serve the static content from the 'build' folder (if that's where your production build output goes)

    # steps:
    # - uses: actions/checkout@v4
    # - name: Login Dockerhub
    #   env:
    #     DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME1}}
    #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD1}}
    #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    # - name: Build the Docker image
    #   run: |
    #     cd frontend
    #     docker build -t iamops1 .
    # - name: Push to Dashboard
    #   run: docker push shripad2587/iamops1:tagname


# name: Build and Push Docker image to Amazon ECR

# on:
#   push:
#     branches:
#       - main  # Trigger the workflow when there is a push to the main branch

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     # Step 1: Checkout the code from GitHub repository
#     - name: Checkout code
#       uses: actions/checkout@v3

#     # Step 2: Set up Docker Buildx
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     # Step 3: Log in to Amazon ECR
#     - name: Log in to Amazon ECR
#       uses: aws-actions/amazon-ecr-login@v1

#     # Step 4: Build the Docker image
#     - name: Build Docker image
#       run: |
#         docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest .

#     # Step 5: Tag the Docker image for ECR
#     - name: Tag Docker image
#       run: |
#         docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

#     # Step 6: Push the Docker image to ECR
#     - name: Push Docker image to ECR
#       run: |
#         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
#         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}


# name: Docker Build and Push to ECR

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
#       - name: Log in to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1  # Make sure to pass the region explicitly here as well



      # # - name: Set up AWS credentials
      # #   uses: aws-actions/configure-aws-credentials@v1
      # #   with:
      # #     aws-access-key-id: ${{ secrets.DOCKER_USERNAME }}
      # #     aws-secret-access-key: ${{ secrets.DOCKER_PASSWORD}}
      # #     aws-region: ap-south-1  # Specify the region where your ECR repository is located



      # - name: Build Docker image
      #   run: |
      #     docker build -t my-app .
        
      # - name: Tag Docker image
      #   run: |
      #     docker tag my-app:latest 873548405156.dkr.ecr.ap-south-1.amazonaws.com/my-repository:latest

      # - name: Push Docker image to ECR
      #   run: |
      #     docker push 873548405156.dkr.ecr.ap-south-1.amazonaws.com/my-repository:latest
